### ISSUE TITLE
WHIP Retracting and Extending bug

### ISSUE THREAD

**Issue by SekiAlpha** [Grezvany13/ILBE-Assault-Pack-Rewrite#3]
**Describe the bug**
When in crouched positions Retracting and Extending the WHIP antenna animation does not animate.

**To Reproduce**
1. Go in-game
2. Equip an ILBE backpack with WHIP antenna.
3. Extend and Retract the antenna using ace.
4. See bug

**Expected behavior**
I expect the animation to Extend and Retract the radio to play when in the crouched position.

**Screenshots / Video**
https://youtu.be/krnYQNng8Ac

**Version:**
 - ILBE version: latest Steam Workshop

**Other Mods:**
-  TFAR: Latest Beta on Steam Workshop (1.0.318)
- ACE3: Latest on Steam workshop.

**Additional context**
HTML file of all the mods used in the video:
https://cdn.discordapp.com/attachments/486300345451020318/631015767382687744/Section_7_Mods_with_Optional_v0.12.0.html

**Comment by Grezvany13** [comment]
This is an issue with `player playAction "medicStop"`, which doesn't seem to work when in a crouch position.

~~I'll change it to another animation (`medicStartRightSide`) which does work from all positions.~~
Ok... seems that the `medicStart*` animations are randomized...
So instead I'll find something more reliable.

**Comment by Grezvany13** [comment]
Fixed with 4ed46a1886e4d993fce6c280709d70319f89e41e
