### ISSUE TITLE
SATCOM enables the Vanilla minedetector

### ISSUE THREAD

**Issue by johnb432** [Grezvany13/ILBE-Assault-Pack-Rewrite#4]
**Describe the bug**
Titles says it: Whenever you have the SATCOM in your inventory, you have access to the Vanilla minedetector.

**To Reproduce**
1. Go into the Virtual Arsenal or ACE Arsenal
2. Get a backpack and put a SATCOM in it.
3. Use the keys for the side panels and open one (brackets or whatever).
4. Minedetector is open.

**Expected behavior**
No minedetecting abilities from a SATCOM.

**Screenshots / Video**
https://imgur.com/gallery/sNn0bDU

**Version:**
 - ILBE version: latest Steam Workshop

**Other Mods:**
-  TFAR: 1.0.325 Beta
- ACE3: 3.13.2 (also occurs without ACE)

**Additional context**
My unit has blacklisted the vanilla minedector and this is a way to circumvent that. I'd like to see the SATCOM stay whitelisted.
My guess is that it comes due to the fact that the SATCOM inherits the Vanilla minedetector's properties (CfgWeapons.hpp, config.bin)?

**Comment by johnb432** [comment]
In fact, this issue persists with all inventory items (antennas).
There is a workaround however: https://github.com/CBATeam/CBA_A3/pull/744.

**Comment by johnb432** [comment]
I have managed to remedy this issue with #5 . I have done some testing and it doesn't seem to interfere with anything.

**Comment by Grezvany13** [comment]
PR is merged and Workshop has been updated.
Thank you for the PR!!!
